### ISSUE TITLE
How to train on other data sets for different action classifications. 

### ISSUE THREAD

**Issue by yurochang** [LZQthePlane/Online-Realtime-Action-Recognition-based-on-OpenPose#1]
Thanks for your cool work, II want to ask how to use this method on other action classifications, how to prepare the data set and train them?

**Comment by LZQthePlane** [comment]
> Thanks for your cool work, II want to ask how to use this method on other action classifications, how to prepare the data set and train them?

I just update my `README.md` and `main.py` for data-collectiong and training，you can check there.
Thanks for your request.

**Comment by yurochang** [comment]
I try your model and my model, they both generate the same problem:
In your model, what ever person do, the only detection result is "walk"; In my test, there is also only one detection result, too. I found that this is also the label "2" in my action_enum. So I reduce the enum to only 0 and 1. The "pred" in "recognizer" module still only generate "2" and cause a crash. I don't know why the action classifier only detect label "2"?

**Comment by LZQthePlane** [comment]
> I try your model and my model, they both generate the same problem:
> In your model, what ever person do, the only detection result is "walk"; In my test, there is also only one detection result, too. I found that this is also the label "2" in my action_enum. So I reduce the enum to only 0 and 1. The "pred" in "recognizer" module still only generate "2" and cause a crash. I don't know why the action classifier only detect label "2"?

1. For the first problem. my model of action recognizing was trained and test in a specific environment, which means the resolution/positions/angles...of the camera and person were designed. so if your trial of test is not just as same as mine, it may result in problems.
2. The Enum of actions in my code are just for showing labels, changing it won't make sense if you use the model I trained. 
So, the best way is retrained the model with your own dataset, collecting the data in your specific environment. My work is just a pipline of experiment. Hope it will help you.

**Comment by yurochang** [comment]
> > I try your model and my model, they both generate the same problem:
> > In your model, what ever person do, the only detection result is "walk"; In my test, there is also only one detection result, too. I found that this is also the label "2" in my action_enum. So I reduce the enum to only 0 and 1. The "pred" in "recognizer" module still only generate "2" and cause a crash. I don't know why the action classifier only detect label "2"?
> 
> 1. For the first problem. my model of action recognizing was trained and test in a specific environment, which means the resolution/positions/angles...of the camera and person were designed. so if your trial of test is not just as same as mine, it may result in problems.
> 2. The Enum of actions in my code are just for showing labels, changing it won't make sense if you use the model I trained.
>    So, the best way is retrained the model with your own dataset, collecting the data in your specific environment. My work is just a pipline of experiment. Hope it will help you.

The crazy part is that when my training data only have 2 labels, the 'pred' still generate the '2', but 2 should not exist!

**Comment by yurochang** [comment]
> > I try your model and my model, they both generate the same problem:
> > In your model, what ever person do, the only detection result is "walk"; In my test, there is also only one detection result, too. I found that this is also the label "2" in my action_enum. So I reduce the enum to only 0 and 1. The "pred" in "recognizer" module still only generate "2" and cause a crash. I don't know why the action classifier only detect label "2"?
> 
> 1. For the first problem. my model of action recognizing was trained and test in a specific environment, which means the resolution/positions/angles...of the camera and person were designed. so if your trial of test is not just as same as mine, it may result in problems.
> 2. The Enum of actions in my code are just for showing labels, changing it won't make sense if you use the model I trained.
>    So, the best way is retrained the model with your own dataset, collecting the data in your specific environment. My work is just a pipline of experiment. Hope it will help you.

Thank you, I found what's the point!

**Comment by zhangdengp** [comment]
i change classes to 2 ,but when i run main.py ,valueError :2 is not a valid Action, and cause a crash.
have you solve it? @yurochang 
thank you

**Comment by ajithvcoder** [comment]
@yurochang  Were u able to implement it for custom datasets and actions
