### ISSUE TITLE
Why do you do pedestrian detection and tracking

### ISSUE THREAD

**Issue by 1298826844** [LZQthePlane/Online-Realtime-Action-Recognition-based-on-OpenPose#13]
I have glanced at the description of OpenPose.The function of 2D real-time multi-person keypoint detection have been done by OpenPose.Why do you detect persons and track them to recognitize pose of one person?Why not detect the skeletons of multiple persons using openpose directly?It is skeletons that pose recognition based on，isn't it?Thank you for answering my questions.
(ps:I am a newcomer of picture processing.So maybe my ideas are wrong.)

**Comment by LZQthePlane** [comment]
sorry, I didn't get your point
