### ISSUE TITLE
Testing:wrong detection

### ISSUE THREAD

**Issue by HARIHARAN1103** [LZQthePlane/Online-Realtime-Action-Recognition-based-on-OpenPose#15]
Hi, I have trained the model with only "sit" action with 2500 samples. I have an issue that model detects the other actions also as sit. Is there any solution to detect other actions as "N/A" without making 2 class label in training  ("sit" and "N/A"). Find the results( only one action has been trained, where results shows every other action as "sit") below.
![Screenshot from 2019-04-05 10-39-02](https://user-images.githubusercontent.com/35688511/55605174-eaefc500-5790-11e9-8c00-3e38b7c4fec7.png)

**Comment by jiajern** [comment]
Since you only trained the model with the action "sit" only. The model has never seen other action at all therefore it will recognize all the action as "sit". If you want the model differentiate a "sit" and a "N/A", then you need to train the model with "N/A" action.

**Comment by ajithvcoder** [comment]
@HARIHARAN1103 i trained with the original git repo i am getting only operate did u get any other out put like stand , walk etc ?
