### ISSUE TITLE
关于行为分类特征向量的组织方式

### ISSUE THREAD

**Issue by XunChangqing** [LZQthePlane/Online-Realtime-Action-Recognition-based-on-OpenPose#16]
Hi，
  我学习了一下代码，请教一个问题。代码中行为分类的特征向量是
`record_joints_norm += [round(center_x/1280, 2), round(center_y/720, 2)]`
  这个归一化向量是不是对位置敏感呢？比如同样的姿势（Action），目标站在画面不同位置，特征向量是不同的吧？这样跟我们的目标是不是不太相同，因为我们显然希望不管目标站在画面何处，只要动作相同，分类都是相同的。

谢谢您的贡献和时间：）

**Comment by LZQthePlane** [comment]
你是对的，我为了数据采集的方便 使用的是比较简单的骨架特征向量。
如果想要获取对位置不敏感的特征，可以考虑crop bounding box，训练的时候仅用有人的那部分crop。

**Comment by XunChangqing** [comment]
谢谢答复
