### ISSUE TITLE
OpenCV videocapture is super slow 

### ISSUE THREAD

**Issue by kevinNejad** [LZQthePlane/Online-Realtime-Action-Recognition-based-on-OpenPose#20]
Hi, Thanks for the great implementation.
However, it is super slow on my laptop (FPS 0.5 ). I dont't have NVIDIA GPU, so I was wondering if this is the issue ?
I appreciate if you help me to fix it.
My system configuration:
OS: Ubunutu 18.04
CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
GPU: Intel® UHD Graphics 620
RAM: 16GB

thanks

**Comment by kevinNejad** [comment]
It got fixed when I used a laptop with GeForce 1080 :)

**Comment by aniquazereen** [comment]
> It got fixed when I used a laptop with GeForce 1080 :)

How did you run with gpu? what is the command or code?
