### ISSUE TITLE
num class issue

### ISSUE THREAD

**Issue by Jaouedi** [LZQthePlane/Online-Realtime-Action-Recognition-based-on-OpenPose#23]
Hello ,
Please when i changed the enum of action in the units i have this erreur : Error when checking target: expected dense_4 to have shape (14,) but got array with shape (4,)

Please can you help me

**Comment by LZQthePlane** [comment]
you didnt change the number of units from 4 to 14 in network dense_4 layer

**Comment by Jaouedi** [comment]
thank you very much i slove it,  i change the number of units but the erreur is in encoder_Y . it must be 14 
thank you :)
