### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by gljaixuexi** [LZQthePlane/Online-Realtime-Action-Recognition-based-on-OpenPose#25]
When I  run  main.py,the following error occurred. How did I solve it? 
OSError: Unable to open file (unable to open file: name = 'Action/framewise_recognition.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by saimj7** [comment]
did you make sure to clone the entire project on to the same directory?
