### ISSUE TITLE
dataset generate

### ISSUE THREAD

**Issue by Angel113110** [LZQthePlane/Online-Realtime-Action-Recognition-based-on-OpenPose#30]
Dear author
  I have read your instructions about training with own dataset. I also have seen the data you used in your project. The question is the last column class in data.csv is manually generated by yourself?

**Comment by LZQthePlane** [comment]
> Dear author
> I have read your instructions about training with own dataset. I also have seen the data you used in your project. The question is the last column class in data.csv is manually generated by yourself?

yes

**Comment by sdustdk1427** [comment]
@LZQthePlane 请问你是怎么对这18个关键点的数据进行处理的？
