### ISSUE TITLE
Graph file doesn't exist

### ISSUE THREAD

**Issue by immkapoor** [LZQthePlane/Online-Realtime-Action-Recognition-based-on-OpenPose#37]
I can't find VGG_Origin model file in the repository . Instead of .pb file I can only see a shell file there. Can someone please tell me how to load the model. 
The code works with mobilenet model though.

**Comment by saimj7** [comment]
@immkapoor you can download from here: https://pan.baidu.com/s/1XT8pHtNP1FQs3BPHgD5f-A#list/path=%2Fsharelink1864347102-902260820936546%2Fopenpose%2Fopenpose%20graph%20model%20coco&parentPath=%2Fsharelink1864347102-902260820936546

**Comment by immkapoor** [comment]
@saimj7 Thank you

**Comment by miliner** [comment]
The link is invalid. Can you republish it

**Comment by sdde5** [comment]
The link is invalid. Can you republish it
