### ISSUE TITLE
ValueError: Error when checking target : expected dense_4 to have shape (5,) but got array with shape (1,)

### ISSUE THREAD

**Issue by HARIHARAN1103** [LZQthePlane/Online-Realtime-Action-Recognition-based-on-OpenPose#7]
I have tried this model for my own data set (i have given sit action video and converted to csv file ).
Csv file contains 1000 records. Now in action_enum.py I have only sit action . In train.py file i have changed the  encoder_Y = [0]*744 + [1]*722 + [2]*815 + [3]*1008 to
 encoder_Y = [0]*1000  ( only for sit action ), After changing in train.py file,I got this error. 

- 
![Screenshot (230)](https://user-images.githubusercontent.com/35688511/54103113-2648df00-43f1-11e9-872e-ee674229c872.png)

**Comment by Shanmugavadivelugopal** [comment]
I also tried the same above. please suggest solution for the training the model of my own data set.

**Comment by LZQthePlane** [comment]
line 58 in `train.py`: `model.add(Dense(units=4, activation='softmax'))`,
the parameter `units` is the number of your data classes. So just changing it may work.

**Comment by HARIHARAN1103** [comment]
Thanks. I will try it and get back to you if I get any errors
