### ISSUE TITLE
experiment environment

### ISSUE THREAD

**Issue by Luke0426** [LZQthePlane/Online-Realtime-Action-Recognition-based-on-OpenPose#8]
What is your platform configuration？such as GPU and CPU

**Comment by LZQthePlane** [comment]
Windows10 + E5-2603 + Geforce 1080

**Comment by Luke0426** [comment]
Thanks!

**Comment by azhaoaigaga** [comment]
@LZQthePlane May I ask you, my gpu is 1050ti 4gb, can't run this project?

**Comment by LZQthePlane** [comment]
> @LZQthePlane May I ask you, my gpu is 1050ti 4gb, can't run this project?

no, it can't, the computing capability is too low for this.
